# Generated by Django 4.1.1 on 2022-09-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varauskalenteri', '0003_alter_tapahtuma_osallistujat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tapahtuma',
            name='kuvaus',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tapahtuma',
            name='loppu',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
